# Generated by Django 3.1.7 on 2021-12-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='vladislav', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='simpleapp.category'),
            preserve_default=False,
        ),
    ]
